name: Build and Release

on: [ push, workflow_dispatch ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-24.04-arm

    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 配置交叉编译环境
        run: |
          sudo apt update
          sudo apt install -y gcc g++ cmake

      - name: 生成配置文件 (Configuration)
        run: |
          cmake -S . build

      - name: 提取版本号
        id: extract
        run: |
          VERSION_FILE="build/generated/version.h"
          VERSION=$(grep '#define PROJECT_VERSION "' $VERSION_FILE | cut -d'"' -f2)
          
          if [ -z "$VERSION" ]; then
            echo "错误: 无法从 $VERSION_FILE 提取到版本号"
            exit 1
          fi
          echo "解析到的版本号为: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: 生成时间戳与短哈希
        id: vars
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          TIMESTAMP=$(date +'%Y%m%d.%H%M%S')
          echo "short_sha=$SHORT_SHA" >> $GITHUB_OUTPUT
          echo "timestamp=$TIMESTAMP" >> $GITHUB_OUTPUT

      - name: 编译项目
        run: |
          cmake --build build

      - name: 设置发布变量
        id: rel_params
        run: |
          VERSION="${{ steps.extract.outputs.version }}"
          SHORT_SHA="${{ steps.vars.outputs.short_sha }}"
          TIMESTAMP="${{ steps.vars.outputs.timestamp }}"

          echo "tag_name=${VERSION}" >> $GITHUB_OUTPUT

          if [ "${{ github.event_name }}" = "push" ]; then
            echo "is_prerelease=true" >> $GITHUB_OUTPUT
            echo "release_name=${VERSION}.${TIMESTAMP}.${SHORT_SHA}" >> $GITHUB_OUTPUT
          else
            echo "is_prerelease=false" >> $GITHUB_OUTPUT
            echo "release_name=${VERSION}" >> $GITHUB_OUTPUT
          fi

      - name: 滚动更新 Tag
        if: github.event_name == 'push'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag -f ${{ steps.rel_params.outputs.tag_name }}
          git push origin ${{ steps.rel_params.outputs.tag_name }} --force

      - name: 创建并上传 GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.rel_params.outputs.tag_name }}
          name: ${{ steps.rel_params.outputs.release_name }}
          prerelease: ${{ steps.rel_params.outputs.is_prerelease == 'true' }}
          target_commitish: ${{ github.sha }}
          files: |
            build/asc
